name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
# allow manual trigger

env:
  ProjName: upc_r2

jobs:
  build:
    runs-on: windows-latest
    permissions: read-all

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Add GitHub NuGet Source
      run: dotnet nuget add source https://nuget.pkg.github.com/ServerEmus/index.json --name "github" --username "any" --password ${{ secrets.GITHUB_TOKEN  }} --store-password-in-clear-text

    - name: Build X64
      run: dotnet publish ${{ env.ProjName }}/${{ env.ProjName }}.csproj -r win-x64 -c:Release -p:Platform=x64 -o Out

    - name: Build X86
      run: dotnet publish ${{ env.ProjName }}/${{ env.ProjName }}.csproj -r win-x86 -c:Release -p:Platform=x86 -o Out

    - name : Sign
      uses: dlemstra/code-sign-action@v1
      with:
        certificate: '${{ secrets.ServerEmusSign_PFX }}'
        folder: 'Out'
        recursive: true

    - name : Upload
      uses: actions/upload-artifact@v4.3.5
      with:
        name: ${{ env.ProjName }}
        path: Out/*